name: 'Flutter mama 👵'
description: 'Checks for tests and code structure'
author: 'crossplatformsweden'

outputs:
  missingTests:
    description: 'Boolean indicating if there are missing test files'
  missingArray:
    description: 'JSON array of missing test files information'

inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
